# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_management_pb2 as worker__management__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerManagementStub(object):
    """Worker Management Service
    用于 Python workers 向 C++ Ingress 注册模型
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/anyserve.WorkerManagement/RegisterModel',
                request_serializer=worker__management__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=worker__management__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.UnregisterModel = channel.unary_unary(
                '/anyserve.WorkerManagement/UnregisterModel',
                request_serializer=worker__management__pb2.UnregisterModelRequest.SerializeToString,
                response_deserializer=worker__management__pb2.UnregisterModelResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/anyserve.WorkerManagement/Heartbeat',
                request_serializer=worker__management__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__management__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class WorkerManagementServicer(object):
    """Worker Management Service
    用于 Python workers 向 C++ Ingress 注册模型
    """

    def RegisterModel(self, request, context):
        """注册模型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterModel(self, request, context):
        """注销模型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker 心跳
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=worker__management__pb2.RegisterModelRequest.FromString,
                    response_serializer=worker__management__pb2.RegisterModelResponse.SerializeToString,
            ),
            'UnregisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterModel,
                    request_deserializer=worker__management__pb2.UnregisterModelRequest.FromString,
                    response_serializer=worker__management__pb2.UnregisterModelResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=worker__management__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__management__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'anyserve.WorkerManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('anyserve.WorkerManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerManagement(object):
    """Worker Management Service
    用于 Python workers 向 C++ Ingress 注册模型
    """

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/anyserve.WorkerManagement/RegisterModel',
            worker__management__pb2.RegisterModelRequest.SerializeToString,
            worker__management__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/anyserve.WorkerManagement/UnregisterModel',
            worker__management__pb2.UnregisterModelRequest.SerializeToString,
            worker__management__pb2.UnregisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/anyserve.WorkerManagement/Heartbeat',
            worker__management__pb2.HeartbeatRequest.SerializeToString,
            worker__management__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
