# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_management.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17worker_management.proto\x12\x08\x61nyserve\"l\n\x14RegisterModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x16\n\x0eworker_address\x18\x03 \x01(\t\x12\x11\n\tworker_id\x18\x04 \x01(\t\"9\n\x15RegisterModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"V\n\x16UnregisterModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\t\";\n\x17UnregisterModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x13\n\x0bmodel_names\x18\x02 \x03(\t\"$\n\x11HeartbeatResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x32\x88\x02\n\x10WorkerManagement\x12R\n\rRegisterModel\x12\x1e.anyserve.RegisterModelRequest\x1a\x1f.anyserve.RegisterModelResponse\"\x00\x12X\n\x0fUnregisterModel\x12 .anyserve.UnregisterModelRequest\x1a!.anyserve.UnregisterModelResponse\"\x00\x12\x46\n\tHeartbeat\x12\x1a.anyserve.HeartbeatRequest\x1a\x1b.anyserve.HeartbeatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERMODELREQUEST']._serialized_start=37
  _globals['_REGISTERMODELREQUEST']._serialized_end=145
  _globals['_REGISTERMODELRESPONSE']._serialized_start=147
  _globals['_REGISTERMODELRESPONSE']._serialized_end=204
  _globals['_UNREGISTERMODELREQUEST']._serialized_start=206
  _globals['_UNREGISTERMODELREQUEST']._serialized_end=292
  _globals['_UNREGISTERMODELRESPONSE']._serialized_start=294
  _globals['_UNREGISTERMODELRESPONSE']._serialized_end=353
  _globals['_HEARTBEATREQUEST']._serialized_start=355
  _globals['_HEARTBEATREQUEST']._serialized_end=413
  _globals['_HEARTBEATRESPONSE']._serialized_start=415
  _globals['_HEARTBEATRESPONSE']._serialized_end=451
  _globals['_WORKERMANAGEMENT']._serialized_start=454
  _globals['_WORKERMANAGEMENT']._serialized_end=718
# @@protoc_insertion_point(module_scope)
